import { createApp } from 'vue';
import App from './App.vue';
import { router } from './router';
import { Button,Cell,Switch, CellGroup,Col,Row,Popup,Space,Toast,Calendar, Swipe,SwipeItem, CountDown,Dialog ,Checkbox,CheckboxGroup,DatetimePicker,Collapse,CollapseItem  ,Field, Form,NumberKeyboard,Picker,Radio,RadioGroup} from 'vant';
import 'vant/es/toast/style';
import DemoBlock from "@/view/mobile/components/DemoBlock";
import DemoSection from "@/view/mobile/components/DemoSection";
const app = createApp(App);
app.use(router);
app.use(Button);
app.use(Cell);
app.use(CellGroup);
app.use(Col);
app.use(Row);
app.use(Popup);
app.use(Space);
app.use(Toast);
app.use(Calendar);
app.use(Checkbox);
app.use(CheckboxGroup);
app.use(DatetimePicker);
app.use(Field);
app.use(Form);
app.use(NumberKeyboard);
app.use(Picker);
app.use(Radio);
app.use(RadioGroup);
app.use(Switch);
app.use(Dialog);
app.use(Collapse);
app.use(CollapseItem);
app.use(CountDown);
app.use(Swipe);
app.use(SwipeItem);
app.component(DemoBlock.name, DemoBlock);
app.component(DemoSection.name, DemoSection);
app.mount('#app');